# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70bff17f63fc926ccfb387c9b139db883f1151e686b19e9f9e71e0128d92f214bdeb7da759918dc36c3ab0d8e71d2de254329a19f7ca21afc9e943e22e009a54

test:
  secret_key_base: 846d14484a9b42b3d1df26bff75deed787127d16f71c7d502de7cc2802b07b6bab8c1a1b53856166b2ae5f0010ed3a8ee909805a6eae06b7eb438cf8500bf2aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
